name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Running Lint
        run: npm run lint

      - name: Running Tests
        run: npm run test

      - name: Running Build
        run: npm run build
